"""Generate client authoring rules from the engine's static contracts."""

import argparse
import json
import runpy
from dataclasses import asdict
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]


def generated_files():
    namespace = runpy.run_path(
        str(ROOT / "vllm-steer/vllm/model_hooks/steering/capabilities.py")
    )
    catalog = {
        name: asdict(cap) for name, cap in namespace["ALGORITHM_CAPABILITIES"].items()
    }
    data = json.dumps(catalog, indent=2) + "\n"
    yield ROOT / "hf-space/algorithm_capabilities.json", data
    yield (
        ROOT / "frontend/app/src/lib/algorithmCapabilities.ts",
        (
            "// Generated by tools/export_client_contracts.py; do not edit.\n"
            "export const ALGORITHM_CAPABILITIES = " + data.rstrip() + " as const;\n"
        ),
    )


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    stale = []
    for path, content in generated_files():
        if args.check:
            if not path.exists() or path.read_text() != content:
                stale.append(str(path.relative_to(ROOT)))
        else:
            path.write_text(content)
    if stale:
        parser.exit(
            1,
            "Run tools/export_client_contracts.py to update: "
            + ", ".join(stale)
            + "\n",
        )


if __name__ == "__main__":
    main()
